name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Unzip Project
        run: |
          unzip EnglishFromZero_Project_Full_Games.zip
          cd EnglishFromZero_Project_Full_Games
          chmod +x gradlew
      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: EnglishFromZero_Project_Full_Games/app/build/outputs/apk/debug/app-debug.apk
